### ISSUE TITLE
Color fades with JointBilateral 1.0.2

### ISSUE THREAD

**Issue by yeezylife** [Artoriuz/glsl-joint-bilateral#3]
This actually happened before when I try to tweak it sharper by myself.

JointBilateral distance_coeff 2.0 intensity_coeff 64:

![JointBilateral2 0 64](https://github.com/Artoriuz/glsl-joint-bilateral/assets/30175425/19bd81a7-a990-45a4-8884-b9f35c35acb1)

JointBilateral distance_coeff 2.5 intensity_coeff 128:

![Joint 2 5 128](https://github.com/Artoriuz/glsl-joint-bilateral/assets/30175425/b63aa591-b240-4c5b-aec9-00fc873af6eb)

You can tell it with your eye that the color yellow is clearly faded (with distance_coeff 2.5 intensity_coeff 128)

Yet on other part of the test image,the sharper shader does give a sharper result.

I just wonder how could the color fade so obviously with a sharper shader...

This doesn't seem to happen with FastBilateral 1.0.1 and 1.0.2 by the way.

----------------------------------------------------------------------------------------
Test image that I used for chroma upscale:
https://github.com/hooke007/MPV_lazy/blob/obs/Temp/IMG/chroma-420.jpg

**Comment by yeezylife** [comment]
Some tests  with FastBilateral.At least the color yellow 'looks' identical.

FastBilateral intensity_coeff 64

![FastBilateral 64 ](https://github.com/Artoriuz/glsl-joint-bilateral/assets/30175425/273fefa0-6c15-4139-b7e9-124aef7b7710)

FastBilateral intensity_coeff 128

![fast 128](https://github.com/Artoriuz/glsl-joint-bilateral/assets/30175425/bc519b1b-a945-46d1-a0cc-23ca8794b5ef)

**Comment by Artoriuz** [comment]
I think this is the kind of problem that you'll only see on this test image. The tighter default of 128.0 makes the shader prefer chroma values from pixels that are closer in luma, and, since JointBilateral has a larger radius, it can grab values from very far away.

This is the output of `--cscale=box`, and it's easy to see that not all of these yellow letters actually have yellow chroma:
![box](https://github.com/Artoriuz/glsl-joint-bilateral/assets/12078193/7350104a-1b78-4e16-9ea9-8aa1b89e8b21)

What's happening here is that JointBilateral "sees" this and weights white more strongly than it weights yellow for pixels "on top of white".

The new defaults did give an improvement in the test image I tried them with, but maybe they wouldn't be universally better. I guess I could revert the change and leave this kind of tweaking to you guys.

**Comment by yeezylife** [comment]
Maybe this test image is too extreme. 

And FastBilateral intensity_coeff 128 seems generally better than 64.
Also JointBilateral 1.0.2 does get higher SSIM score than 1.0.1 (even though these yellow letters look faded in the test image). I guess that's because SSIM weights sharpness much more than color.

Anyway these two shaders are pretty good.Very good result and doesn't consume much resource at all.

**Comment by hooke007** [comment]
@Artoriuz The current state seems strange. https://github.com/Artoriuz/glsl-joint-bilateral/commit/7c8d5b6c720698fb28e6013832287488db5cd0f7

![MPV-00_00_00 000-N0001](https://github.com/Artoriuz/glsl-joint-bilateral/assets/41094733/83c3e2cb-c3ae-431d-b706-0b8590a789c3)

**Comment by yeezylife** [comment]
I noticed this too, but it seems alright in regular movie scenes. And I've changed to CfL now...

**Comment by Artoriuz** [comment]
Yeah... Seems like the bilateral gaussian function returns numbers that are a little too low sometimes, and that makes the pixels explode later. Limiting the weights to 1e-32 fixes the issue.

Lowering `intensity_coeff` down to 256.0 makes the shader a little better on this test image as well...

**Comment by Artoriuz** [comment]
Fixed https://github.com/Artoriuz/glsl-joint-bilateral/commit/c76455c77b7d23e2d5ed83353d4bd0fae447aa12,
